"""
Response models and structured data contracts for The Blind Spot.
"""


from pydantic import BaseModel, Field


class OverlookedFactor(BaseModel):
    """An important factor not explicitly considered, tied to the user's situation."""
    factor: str = Field(..., description="The specific overlooked dimension or consequence.")
    why_it_matters: str = Field(..., description="Why this factor is important to their situation.")


class UnstatedAssumption(BaseModel):
    """An unstated assumption in the user's reasoning."""
    assumption: str = Field(..., description="The hidden hypothesis or assumption being made.")
    how_to_test: str = Field(..., description="A concrete question or step to test whether this assumption holds.")


class InternalConflict(BaseModel):
    """Tension or contradiction where the user's own statements pull in different directions."""
    conflict_description: str = Field(..., description="Description of the tension between priorities or statements.")
    user_quotes: list[str] = Field(
        default_factory=list,
        description="Direct or paraphrased excerpts of the user's statements that illustrate the tension.",
    )


class BlindSpotAnalysisResponse(BaseModel):
    """
    Complete analysis payload generated by the Socratic cognitive mirror.
    Strictly forbids verdict or advice language.
    """
    session_id: str = Field(..., description="Unique session identifier for the thought session.")
    what_you_emphasized: list[str] = Field(
        ...,
        description="The primary factors and visible attributes the user explicitly focused on.",
    )
    overlooked_factors: list[OverlookedFactor] = Field(
        ...,
        description="Crucial factors not mentioned in the prompt that carry significant weight.",
    )
    unstated_assumptions: list[UnstatedAssumption] = Field(
        ...,
        description="Implicit premises the decision rests upon without concrete validation.",
    )
    internal_conflicts: list[InternalConflict] = Field(
        ...,
        description="Points where the user's own criteria, priorities, or desires clash.",
    )
    other_perspective: str = Field(
        ...,
        description="The strongest possible case for the alternative or counter-option.",
    )
    probing_questions: list[str] = Field(
        ...,
        description="5 to 7 open Socratic questions arranged from most revealing to deeper inquiry.",
    )
    disclaimer: str = Field(
        ...,
        description="Ethical disclaimer reinforcing that this is a thinking aid, not decision advice.",
    )


class FollowupResponse(BaseModel):
    """Response returned when a user answers a probing question."""
    session_id: str = Field(..., description="Session identifier.")
    user_answer_summary: str = Field(..., description="Objective summary of what the user articulated.")
    deeper_questions: list[str] = Field(
        ...,
        description="1 to 3 deeper follow-up questions provoked by their reflection.",
    )
    newly_exposed_blind_spots: list[str] = Field(
        default_factory=list,
        description="Newly surfaced subtle assumptions or blind spots from their answer.",
    )
    reflection_step: int = Field(default=1, description="Current reflection iteration count.")


class ReasoningMapResponse(BaseModel):
    """Exportable summary built strictly from the user's confirmed inputs."""
    markdown_content: str = Field(..., description="Rendered markdown document of user's reasoning map.")
    confirmed_assumptions_count: int = Field(..., description="Number of confirmed assumptions.")
    acknowledged_conflicts_count: int = Field(..., description="Number of acknowledged conflicts.")
    open_questions_count: int = Field(..., description="Number of open probing questions remaining.")
    empty_decision_line: str = Field(
        default="My decision: __________________________________________________",
        description="Unfilled decision line ensuring the AI never decides.",
    )


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "ok"
    app_name: str
    version: str
    model: str
    gemini_configured: bool


class ErrorResponse(BaseModel):
    """Standardized error payload."""
    detail: str
    code: str | None = None
